#!/bin/bash

# @todo We need to do more checking of the command line args
# --config
#	update		Change the version of flint used by default
# --version		Temporarily use a different version of flint

FLINTLOCK=.flintlock

if [[ ! -f $FLINTLOCK ]]; then
	printf "stable\n" > $FLINTLOCK
fi

if [[ $1 == "--config" ]]; then
	if [[ $2 == "update" ]]; then
		# Proposed versions
		# custom:	path to custom build
		# nightly:	latest nightly build
		# stable:	latest stable build
		# VERSION:	VERSION of flint
		# Running without a given version sets it to the VERSION of latest

		# @todo Make sure this is actually a valid version somehow
		if [[ ! -z $3 ]]; then

			printf "$3" > $FLINTLOCK
			if [[ $3 == "custom" ]]; then
				printf " $4" >> $FLINTLOCK
			fi
			printf "\n" >> $FLINTLOCK

			printf "Flint will now use version: $3\n"
		else
			printf "Getting current latest version\n"
		fi
	else
		printf "Welcome to config mode!\n"
		# @todo Show a list of commands
	fi
else
	VERSION=$(awk '{print $1}' $FLINTLOCK)
	FLINT_PATH=.flint
	DEBUG=""
	ARGS=$@

	if [[ $1 == "--version" ]]; then
		VERSION=$2

		if [[ $VERSION == "custom" ]]; then
			FLINT_PATH=$3
			ARGS=${@:4}
		else
			ARGS=${@:3}
		fi
	fi

	printf "Flint: $VERSION\n"

	if [[ $VERSION == "custom" ]]; then
		printf "Path: $FLINT_PATH\n"
		FLINT_PATH=$(awk '{print $2}' $FLINTLOCK)

		if [[ $1 == "--debug-flint" ]]; then
			DEBUG="gdb --args"
			ARGS=${@:2}
		fi

	else

		mkdir -p .flint

		wget https://downloads.mtgames.nl/release/flint/$VERSION/checksum -O .flint/checksum -q

		if [ -f .flint/flint ]; then
			(cd .flint && sha256sum --check checksum >> /dev/null)
		else
			false
		fi

		# @todo Make sure that if the checksum download fails for whatever reason that we just continue with the current version
		if [ $? -eq 0 ]; then
			printf "Flint is up-to-date\n"
		else
			# @todo Display download progress
			printf "Downloading flint\n"
			wget https://downloads.mtgames.nl/release/flint/$VERSION/flint -O .flint/flint  -q --show-progress
			chmod +x .flint/flint
		fi
		rm .flint/checksum

	fi
	LD_LIBRARY_PATH=$FLINT_PATH $DEBUG $FLINT_PATH/flint $ARGS
fi
